name: iOS Real Device Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
    ios-real-device:
      runs-on: self-hosted
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Check Python version
          run: python3 --version
                
        - name: Install dependencies
          run: |
                python3 -m pip install -r requirements.txt
                
        - name: Check Appium
          run: |
            appium -v
            appium driver list --installed
                
        - name: Check connected devices
          run: |
                echo "Available devices:"
                xcrun xctrace list devices
                
        - name: Create .env for tests
          if: always()
          run: |
            echo "STANDART_USER=${{ secrets.STANDART_USER }}" >> .env
            echo "STANDART_PASSWORD=${{ secrets.STANDART_PASSWORD }}" >> .env
            echo "LOCKED_OUT_USER=${{ secrets.LOCKED_OUT_USER }}" >> .env
            echo "LOCKED_USER_PASSWORD=${{ secrets.LOCKED_USER_PASSWORD }}" >> .env
            echo "PROBLEM_USER=${{ secrets.PROBLEM_USER }}" >> .env
            echo "PROBLEM_USER_PASSWORD=${{ secrets.PROBLEM_USER_PASSWORD }}" >> .env
      
        - name: Start Appium
          run: |
                echo "Starting Appium..."
                appium --log-level info &
                sleep 10
        - name: Run iOS tests
          run: |
                pytest -v -s

        - name: Generate Allure report
          if: always()
          run: |
                allure generate allure-results -o allure-report --clean
                echo "Allure report available at:"
                echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

