name: iOS Real Device Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # каждые 6 часов
  workflow_dispatch:

jobs:
    ios-real-device:
      runs-on: self-hosted
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Check Python version
          run: python3 --version
                
        - name: Install dependencies
          run: |
                python3 -m pip install -r requirements.txt
                
        - name: Check Appium
          run: |
            appium -v
            appium driver list --installed
                
        - name: Check connected devices
          run: |
                echo "Available devices:"
                xcrun xctrace list devices
      
        - name: Start Appium
          run: |
                echo "Starting Appium..."
                appium --log-level info &
                sleep 10
        - name: Run iOS tests
          run: |
                pytest -v -s

        - name: Generate Allure report
          if: always()
          run: |
                allure generate allure-results -o allure-report --clean

